/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.EscreverELer;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import javax.swing.JOptionPane;
import controller.InfosGlobais;
import controller.TelaAddFuncaoController;
import controller.TelaPrincipalController;
import java.awt.Toolkit;

/**
 *
 * @author Caique
 */
public class TelaAddFuncao extends javax.swing.JFrame {

    /**
     * Creates new form TelaAddFuncao
     */
    public TelaAddFuncao() {
        initComponents();
        TelaPrincipalController.isTelaAddFuncao = this;
        setIconeTela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfDescricao = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        btAdicionar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem2");
        jPopupMenu1.add(jMenuItem1);

        setDefaultCloseOperation(fecharTela());
        setTitle("Adicionar Função");
        setBackground(new java.awt.Color(153, 153, 153));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jScrollPane1.setBackground(new java.awt.Color(51, 51, 51));

        tfDescricao.setBackground(new java.awt.Color(51, 51, 51));
        tfDescricao.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Adicione uma DESCRIÇÃO a essa Função", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12), new java.awt.Color(51, 51, 51))); // NOI18N
        tfDescricao.setForeground(new java.awt.Color(51, 51, 51));
        tfDescricao.setSelectionColor(new java.awt.Color(51, 51, 51));
        jScrollPane1.setViewportView(tfDescricao);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        btAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pacoteicones2/add.png"))); // NOI18N
        btAdicionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btAdicionarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btAdicionarMouseExited(evt);
            }
        });
        btAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarActionPerformed(evt);
            }
        });

        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pacoteicones2/cancel.png"))); // NOI18N
        btCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btCancelarMouseExited(evt);
            }
        });
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(btAdicionar)
                .addGap(51, 51, 51)
                .addComponent(btCancelar)
                .addGap(130, 130, 130))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btCancelar)
                    .addComponent(btAdicionar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarActionPerformed
        adicionarFuncao(TelaPrincipalController.caminhoFuncaoAdd,TelaPrincipalController.nomeFuncaoAdd);
    }//GEN-LAST:event_btAdicionarActionPerformed

    private void btAdicionarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAdicionarMouseEntered
        TelaAddFuncaoController.mostrarPopUp("Adicionar Função", evt, btAdicionar);
    }//GEN-LAST:event_btAdicionarMouseEntered

    private void btAdicionarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAdicionarMouseExited
        TelaAddFuncaoController.ocultarPopUp();
    }//GEN-LAST:event_btAdicionarMouseExited

    private void btCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCancelarMouseEntered
        TelaAddFuncaoController.mostrarPopUp("Cancelar", evt, btCancelar);
    }//GEN-LAST:event_btCancelarMouseEntered

    private void btCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCancelarMouseExited
        TelaAddFuncaoController.ocultarPopUp();
    }//GEN-LAST:event_btCancelarMouseExited

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        fecharTela();
    }//GEN-LAST:event_btCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAddFuncao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAddFuncao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAddFuncao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAddFuncao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAddFuncao().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionar;
    private javax.swing.JButton btCancelar;
    public static javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextPane tfDescricao;
    // End of variables declaration//GEN-END:variables
    
    public  void adicionarFuncao(String caminhoArquivoAdd,String nomeDaFuncaoAdd){
        String descDaFuncao = "";
        if(tfDescricao.getText().isEmpty()){
            descDaFuncao = "Nenhuma";
        }else{
            descDaFuncao = tfDescricao.getText();
        }
        
        if(descDaFuncao.contains("=")){
            JOptionPane.showMessageDialog(null, "A Descrição da Função NÃO pode conter o Caracter especial : '=' (Sinal de Igual)","Aviso",JOptionPane.ERROR_MESSAGE);
        }else{
            String dados = EscreverELer.ler(InfosGlobais.getCaminhoPadraoLista());
            if (dados.isEmpty()) {
                dados = nomeDaFuncaoAdd + ";" + descDaFuncao;
            } else {
                dados = dados + "=" + nomeDaFuncaoAdd + ";" + descDaFuncao;
            }
            EscreverELer.escrever(InfosGlobais.getCaminhoPadraoLista(), dados);
            JOptionPane.showMessageDialog(null, "Função Adicionada a Lista.");
            try {
                Path temp = Files.move(Paths.get(caminhoArquivoAdd),
                        Paths.get(InfosGlobais.getCaminhoPadraoFuncoes() + nomeDaFuncaoAdd));

                JOptionPane.showMessageDialog(null, "Função Adicionada com Sucesso.");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao Adicionar Função a Area de Funções.");
            }
            TelaPrincipalController.buscarDados();
            fecharTela();
        }
    }

    public int fecharTela(){
        TelaPrincipalController.isTelaAddFuncao = null;
        dispose();
        return 1;
    }
    
    private void setIconeTela() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../Pacoteicones2/bot2.png")));
    }
}
